# Generated by Django 4.0.6 on 2022-08-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('booktype', 'booktype'), ('editions', 'editions')], max_length=100),
        ),
    ]
