# Generated by Django 4.0.6 on 2022-08-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('editions', 'editions'), ('booktype', 'booktype')], max_length=100),
        ),
    ]
