# Generated by Django 4.0.6 on 2022-08-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category'),
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
